export const FETCH_PLANETS = 'FETCH_PLANETS';
export const FETCH_PLANETS_START = 'FETCH_PLANETS_START';
export const FETCH_PLANETS_SUCCESS = 'FETCH_PLANETS_SUCCESS';
export const FETCH_PLANETS_FAIL = 'FETCH_PLANETS_FAIL';

export const FETCH_PLANET = 'FETCH_PLANET';
export const FETCH_PLANET_START = 'FETCH_PLANET_START';
export const FETCH_PLANET_SUCCESS = 'FETCH_PLANET_SUCCESS';
export const FETCH_PLANET_FAIL = 'FETCH_PLANET_FAIL';
