export const FETCH_PLANETS = 'FETCH_PLANETS';
export const FETCH_PLANETS_INIT = 'FETCH_PLANETS_INIT';
export const FETCH_PLANETS_START = 'FETCH_PLANETS_START';
export const FETCH_PLANETS_SUCCESS = 'FETCH_PLANETS_SUCCESS';
export const FETCH_PLANETS_FAIL = 'FETCH_PLANETS_FAIL';
